import { Emoji, EmojiCategory } from "./types";

export const EMOJI_DATA: Emoji[] = [
  // Smileys & Emotions
  { emoji: "😀", name: "grinning face", category: "smileys", keywords: ["happy", "smile"] },
  { emoji: "😃", name: "grinning face with big eyes", category: "smileys", keywords: ["happy", "smile"] },
  { emoji: "😄", name: "grinning face with smiling eyes", category: "smileys", keywords: ["happy", "smile"] },
  { emoji: "😁", name: "beaming face with smiling eyes", category: "smileys", keywords: ["happy", "grin"] },
  { emoji: "😆", name: "grinning squinting face", category: "smileys", keywords: ["happy", "laugh"] },
  { emoji: "😅", name: "grinning face with sweat", category: "smileys", keywords: ["nervous", "sweat"] },
  { emoji: "🤣", name: "rolling on the floor laughing", category: "smileys", keywords: ["lol", "laugh"] },
  { emoji: "😂", name: "face with tears of joy", category: "smileys", keywords: ["lol", "laugh", "cry"] },
  { emoji: "🙂", name: "slightly smiling face", category: "smileys", keywords: ["smile"] },
  { emoji: "🙃", name: "upside-down face", category: "smileys", keywords: ["silly", "sarcasm"] },
  { emoji: "😉", name: "winking face", category: "smileys", keywords: ["wink", "flirt"] },
  { emoji: "😊", name: "smiling face with smiling eyes", category: "smileys", keywords: ["blush", "happy"] },
  { emoji: "😇", name: "smiling face with halo", category: "smileys", keywords: ["angel", "innocent"] },
  { emoji: "🥰", name: "smiling face with hearts", category: "smileys", keywords: ["love", "adore"] },
  { emoji: "😍", name: "smiling face with heart-eyes", category: "smileys", keywords: ["love", "crush"] },
  { emoji: "🤩", name: "star-struck", category: "smileys", keywords: ["wow", "amazing"] },
  { emoji: "😘", name: "face blowing a kiss", category: "smileys", keywords: ["kiss", "love"] },
  { emoji: "😗", name: "kissing face", category: "smileys", keywords: ["kiss"] },
  { emoji: "☺️", name: "smiling face", category: "smileys", keywords: ["happy", "blush"] },
  { emoji: "😚", name: "kissing face with closed eyes", category: "smileys", keywords: ["kiss"] },
  { emoji: "😋", name: "face savoring food", category: "smileys", keywords: ["yummy", "delicious"] },
  { emoji: "😛", name: "face with tongue", category: "smileys", keywords: ["playful", "silly"] },
  { emoji: "😜", name: "winking face with tongue", category: "smileys", keywords: ["playful", "silly"] },
  { emoji: "🤪", name: "zany face", category: "smileys", keywords: ["crazy", "wild"] },
  { emoji: "😝", name: "squinting face with tongue", category: "smileys", keywords: ["playful"] },
  { emoji: "🤑", name: "money-mouth face", category: "smileys", keywords: ["money", "rich"] },
  { emoji: "🤗", name: "hugging face", category: "smileys", keywords: ["hug", "warm"] },
  { emoji: "🤭", name: "face with hand over mouth", category: "smileys", keywords: ["oops", "giggle"] },
  { emoji: "🤫", name: "shushing face", category: "smileys", keywords: ["quiet", "secret"] },
  { emoji: "🤔", name: "thinking face", category: "smileys", keywords: ["think", "hmm"] },
  { emoji: "🤐", name: "zipper-mouth face", category: "smileys", keywords: ["secret", "quiet"] },
  { emoji: "🤨", name: "face with raised eyebrow", category: "smileys", keywords: ["skeptic", "doubt"] },
  { emoji: "😐", name: "neutral face", category: "smileys", keywords: ["meh", "neutral"] },
  { emoji: "😑", name: "expressionless face", category: "smileys", keywords: ["blank", "meh"] },
  { emoji: "😶", name: "face without mouth", category: "smileys", keywords: ["silent", "speechless"] },
  { emoji: "😏", name: "smirking face", category: "smileys", keywords: ["smirk", "sly"] },
  { emoji: "😒", name: "unamused face", category: "smileys", keywords: ["meh", "bored"] },
  { emoji: "🙄", name: "face with rolling eyes", category: "smileys", keywords: ["eyeroll", "annoyed"] },
  { emoji: "😬", name: "grimacing face", category: "smileys", keywords: ["awkward", "nervous"] },
  { emoji: "🤥", name: "lying face", category: "smileys", keywords: ["lie", "pinocchio"] },
  { emoji: "😌", name: "relieved face", category: "smileys", keywords: ["relieved", "calm"] },
  { emoji: "😔", name: "pensive face", category: "smileys", keywords: ["sad", "thoughtful"] },
  { emoji: "😪", name: "sleepy face", category: "smileys", keywords: ["tired", "sleepy"] },
  { emoji: "🤤", name: "drooling face", category: "smileys", keywords: ["drool", "hungry"] },
  { emoji: "😴", name: "sleeping face", category: "smileys", keywords: ["sleep", "zzz"] },
  { emoji: "😷", name: "face with medical mask", category: "smileys", keywords: ["sick", "mask"] },
  { emoji: "🤒", name: "face with thermometer", category: "smileys", keywords: ["sick", "fever"] },
  { emoji: "🤕", name: "face with head-bandage", category: "smileys", keywords: ["hurt", "injured"] },
  { emoji: "🤢", name: "nauseated face", category: "smileys", keywords: ["sick", "nausea"] },
  { emoji: "🤮", name: "face vomiting", category: "smileys", keywords: ["sick", "vomit"] },
  { emoji: "🤧", name: "sneezing face", category: "smileys", keywords: ["sneeze", "sick"] },
  { emoji: "🥵", name: "hot face", category: "smileys", keywords: ["hot", "sweating"] },
  { emoji: "🥶", name: "cold face", category: "smileys", keywords: ["cold", "freezing"] },
  { emoji: "🥴", name: "woozy face", category: "smileys", keywords: ["dizzy", "drunk"] },
  { emoji: "😵", name: "dizzy face", category: "smileys", keywords: ["dizzy", "dead"] },
  { emoji: "🤯", name: "exploding head", category: "smileys", keywords: ["mindblown", "shocked"] },
  { emoji: "🤠", name: "cowboy hat face", category: "smileys", keywords: ["cowboy", "western"] },
  { emoji: "🥳", name: "partying face", category: "smileys", keywords: ["party", "celebrate"] },
  { emoji: "😎", name: "smiling face with sunglasses", category: "smileys", keywords: ["cool", "sunglasses"] },
  { emoji: "🤓", name: "nerd face", category: "smileys", keywords: ["nerd", "glasses"] },
  { emoji: "🧐", name: "face with monocle", category: "smileys", keywords: ["monocle", "fancy"] },
  { emoji: "😕", name: "confused face", category: "smileys", keywords: ["confused", "puzzled"] },
  { emoji: "😟", name: "worried face", category: "smileys", keywords: ["worried", "concerned"] },
  { emoji: "🙁", name: "slightly frowning face", category: "smileys", keywords: ["sad", "frown"] },
  { emoji: "☹️", name: "frowning face", category: "smileys", keywords: ["sad", "frown"] },
  { emoji: "😮", name: "face with open mouth", category: "smileys", keywords: ["surprised", "wow"] },
  { emoji: "😯", name: "hushed face", category: "smileys", keywords: ["surprised", "quiet"] },
  { emoji: "😲", name: "astonished face", category: "smileys", keywords: ["shocked", "amazed"] },
  { emoji: "😳", name: "flushed face", category: "smileys", keywords: ["embarrassed", "blush"] },
  { emoji: "🥺", name: "pleading face", category: "smileys", keywords: ["please", "puppy eyes"] },
  { emoji: "😦", name: "frowning face with open mouth", category: "smileys", keywords: ["sad", "shocked"] },
  { emoji: "😧", name: "anguished face", category: "smileys", keywords: ["anguish", "pain"] },
  { emoji: "😨", name: "fearful face", category: "smileys", keywords: ["scared", "fear"] },
  { emoji: "😰", name: "anxious face with sweat", category: "smileys", keywords: ["anxious", "nervous"] },
  { emoji: "😥", name: "sad but relieved face", category: "smileys", keywords: ["sad", "relieved"] },
  { emoji: "😢", name: "crying face", category: "smileys", keywords: ["sad", "cry"] },
  { emoji: "😭", name: "loudly crying face", category: "smileys", keywords: ["cry", "sob"] },
  { emoji: "😱", name: "face screaming in fear", category: "smileys", keywords: ["scared", "scream"] },
  { emoji: "😖", name: "confounded face", category: "smileys", keywords: ["frustrated"] },
  { emoji: "😣", name: "persevering face", category: "smileys", keywords: ["struggle"] },
  { emoji: "😞", name: "disappointed face", category: "smileys", keywords: ["sad", "disappointed"] },
  { emoji: "😓", name: "downcast face with sweat", category: "smileys", keywords: ["hard work", "stress"] },
  { emoji: "😩", name: "weary face", category: "smileys", keywords: ["tired", "stressed"] },
  { emoji: "😫", name: "tired face", category: "smileys", keywords: ["tired", "exhausted"] },
  { emoji: "🥱", name: "yawning face", category: "smileys", keywords: ["yawn", "tired"] },
  { emoji: "😤", name: "face with steam from nose", category: "smileys", keywords: ["angry", "frustrated"] },
  { emoji: "😡", name: "pouting face", category: "smileys", keywords: ["angry", "rage"] },
  { emoji: "😠", name: "angry face", category: "smileys", keywords: ["angry", "mad"] },
  { emoji: "🤬", name: "face with symbols on mouth", category: "smileys", keywords: ["swear", "angry"] },
  { emoji: "😈", name: "smiling face with horns", category: "smileys", keywords: ["devil", "evil"] },
  { emoji: "👿", name: "angry face with horns", category: "smileys", keywords: ["devil", "angry"] },
  { emoji: "💀", name: "skull", category: "smileys", keywords: ["death", "dead"] },
  { emoji: "☠️", name: "skull and crossbones", category: "smileys", keywords: ["death", "danger"] },
  { emoji: "💩", name: "pile of poo", category: "smileys", keywords: ["poop", "shit"] },
  { emoji: "🤡", name: "clown face", category: "smileys", keywords: ["clown", "circus"] },
  { emoji: "👹", name: "ogre", category: "smileys", keywords: ["monster", "scary"] },
  { emoji: "👺", name: "goblin", category: "smileys", keywords: ["monster", "scary"] },
  { emoji: "👻", name: "ghost", category: "smileys", keywords: ["ghost", "halloween"] },
  { emoji: "👽", name: "alien", category: "smileys", keywords: ["alien", "ufo"] },
  { emoji: "👾", name: "alien monster", category: "smileys", keywords: ["game", "space invader"] },
  { emoji: "🤖", name: "robot", category: "smileys", keywords: ["robot", "ai"] },

  // Gestures & People
  { emoji: "👋", name: "waving hand", category: "gestures", keywords: ["wave", "hello", "bye"] },
  { emoji: "🤚", name: "raised back of hand", category: "gestures", keywords: ["hand"] },
  { emoji: "🖐️", name: "hand with fingers splayed", category: "gestures", keywords: ["hand", "five"] },
  { emoji: "✋", name: "raised hand", category: "gestures", keywords: ["stop", "high five"] },
  { emoji: "🖖", name: "vulcan salute", category: "gestures", keywords: ["spock", "star trek"] },
  { emoji: "👌", name: "OK hand", category: "gestures", keywords: ["ok", "perfect"] },
  { emoji: "🤌", name: "pinched fingers", category: "gestures", keywords: ["italian", "chef"] },
  { emoji: "🤏", name: "pinching hand", category: "gestures", keywords: ["small", "little"] },
  { emoji: "✌️", name: "victory hand", category: "gestures", keywords: ["peace", "v"] },
  { emoji: "🤞", name: "crossed fingers", category: "gestures", keywords: ["luck", "hope"] },
  { emoji: "🤟", name: "love-you gesture", category: "gestures", keywords: ["love", "rock"] },
  { emoji: "🤘", name: "sign of the horns", category: "gestures", keywords: ["rock", "metal"] },
  { emoji: "🤙", name: "call me hand", category: "gestures", keywords: ["call", "shaka"] },
  { emoji: "👈", name: "backhand index pointing left", category: "gestures", keywords: ["left", "point"] },
  { emoji: "👉", name: "backhand index pointing right", category: "gestures", keywords: ["right", "point"] },
  { emoji: "👆", name: "backhand index pointing up", category: "gestures", keywords: ["up", "point"] },
  { emoji: "🖕", name: "middle finger", category: "gestures", keywords: ["rude", "finger"] },
  { emoji: "👇", name: "backhand index pointing down", category: "gestures", keywords: ["down", "point"] },
  { emoji: "☝️", name: "index pointing up", category: "gestures", keywords: ["up", "point"] },
  { emoji: "👍", name: "thumbs up", category: "gestures", keywords: ["like", "good", "yes"] },
  { emoji: "👎", name: "thumbs down", category: "gestures", keywords: ["dislike", "bad", "no"] },
  { emoji: "✊", name: "raised fist", category: "gestures", keywords: ["fist", "power"] },
  { emoji: "👊", name: "oncoming fist", category: "gestures", keywords: ["punch", "fist bump"] },
  { emoji: "🤛", name: "left-facing fist", category: "gestures", keywords: ["fist bump"] },
  { emoji: "🤜", name: "right-facing fist", category: "gestures", keywords: ["fist bump"] },
  { emoji: "👏", name: "clapping hands", category: "gestures", keywords: ["applause", "clap"] },
  { emoji: "🙌", name: "raising hands", category: "gestures", keywords: ["hooray", "celebrate"] },
  { emoji: "👐", name: "open hands", category: "gestures", keywords: ["jazz hands", "hug"] },
  { emoji: "🤲", name: "palms up together", category: "gestures", keywords: ["prayer", "offering"] },
  { emoji: "🤝", name: "handshake", category: "gestures", keywords: ["deal", "agreement"] },
  { emoji: "🙏", name: "folded hands", category: "gestures", keywords: ["pray", "thank you"] },
  { emoji: "✍️", name: "writing hand", category: "gestures", keywords: ["write", "pen"] },
  { emoji: "💪", name: "flexed biceps", category: "gestures", keywords: ["strong", "muscle", "power"] },
  { emoji: "🦾", name: "mechanical arm", category: "gestures", keywords: ["robot", "prosthetic"] },
  { emoji: "🙈", name: "see-no-evil monkey", category: "gestures", keywords: ["monkey", "hide"] },
  { emoji: "🙉", name: "hear-no-evil monkey", category: "gestures", keywords: ["monkey", "deaf"] },
  { emoji: "🙊", name: "speak-no-evil monkey", category: "gestures", keywords: ["monkey", "quiet"] },
  { emoji: "💋", name: "kiss mark", category: "gestures", keywords: ["kiss", "lips"] },
  { emoji: "❤️", name: "red heart", category: "gestures", keywords: ["love", "heart"] },
  { emoji: "🧡", name: "orange heart", category: "gestures", keywords: ["love", "heart"] },
  { emoji: "💛", name: "yellow heart", category: "gestures", keywords: ["love", "heart"] },
  { emoji: "💚", name: "green heart", category: "gestures", keywords: ["love", "heart"] },
  { emoji: "💙", name: "blue heart", category: "gestures", keywords: ["love", "heart"] },
  { emoji: "💜", name: "purple heart", category: "gestures", keywords: ["love", "heart"] },
  { emoji: "🖤", name: "black heart", category: "gestures", keywords: ["love", "heart", "dark"] },
  { emoji: "🤍", name: "white heart", category: "gestures", keywords: ["love", "heart", "pure"] },
  { emoji: "🤎", name: "brown heart", category: "gestures", keywords: ["love", "heart"] },
  { emoji: "💔", name: "broken heart", category: "gestures", keywords: ["heartbreak", "sad"] },
  { emoji: "💕", name: "two hearts", category: "gestures", keywords: ["love", "hearts"] },
  { emoji: "💖", name: "sparkling heart", category: "gestures", keywords: ["love", "sparkle"] },
  { emoji: "💗", name: "growing heart", category: "gestures", keywords: ["love", "heart"] },
  { emoji: "💘", name: "heart with arrow", category: "gestures", keywords: ["cupid", "love"] },
  { emoji: "💝", name: "heart with ribbon", category: "gestures", keywords: ["valentine", "gift"] },
  { emoji: "💟", name: "heart decoration", category: "gestures", keywords: ["love", "heart"] },

  // Animals & Nature
  { emoji: "🐶", name: "dog face", category: "animals", keywords: ["dog", "puppy", "pet"] },
  { emoji: "🐱", name: "cat face", category: "animals", keywords: ["cat", "kitten", "pet"] },
  { emoji: "🐭", name: "mouse face", category: "animals", keywords: ["mouse", "rodent"] },
  { emoji: "🐹", name: "hamster", category: "animals", keywords: ["hamster", "pet"] },
  { emoji: "🐰", name: "rabbit face", category: "animals", keywords: ["rabbit", "bunny"] },
  { emoji: "🦊", name: "fox", category: "animals", keywords: ["fox", "wild"] },
  { emoji: "🐻", name: "bear", category: "animals", keywords: ["bear", "wild"] },
  { emoji: "🐼", name: "panda", category: "animals", keywords: ["panda", "bear"] },
  { emoji: "🐨", name: "koala", category: "animals", keywords: ["koala", "australia"] },
  { emoji: "🐯", name: "tiger face", category: "animals", keywords: ["tiger", "wild"] },
  { emoji: "🦁", name: "lion", category: "animals", keywords: ["lion", "king"] },
  { emoji: "🐮", name: "cow face", category: "animals", keywords: ["cow", "farm"] },
  { emoji: "🐷", name: "pig face", category: "animals", keywords: ["pig", "farm"] },
  { emoji: "🐸", name: "frog", category: "animals", keywords: ["frog", "toad"] },
  { emoji: "🐵", name: "monkey face", category: "animals", keywords: ["monkey", "ape"] },
  { emoji: "🐔", name: "chicken", category: "animals", keywords: ["chicken", "rooster"] },
  { emoji: "🐧", name: "penguin", category: "animals", keywords: ["penguin", "bird"] },
  { emoji: "🐦", name: "bird", category: "animals", keywords: ["bird", "tweet"] },
  { emoji: "🐤", name: "baby chick", category: "animals", keywords: ["chick", "bird"] },
  { emoji: "🦆", name: "duck", category: "animals", keywords: ["duck", "bird"] },
  { emoji: "🦅", name: "eagle", category: "animals", keywords: ["eagle", "bird"] },
  { emoji: "🦉", name: "owl", category: "animals", keywords: ["owl", "wise"] },
  { emoji: "🦇", name: "bat", category: "animals", keywords: ["bat", "vampire"] },
  { emoji: "🐺", name: "wolf", category: "animals", keywords: ["wolf", "wild"] },
  { emoji: "🐗", name: "boar", category: "animals", keywords: ["boar", "pig"] },
  { emoji: "🐴", name: "horse face", category: "animals", keywords: ["horse"] },
  { emoji: "🦄", name: "unicorn", category: "animals", keywords: ["unicorn", "magic"] },
  { emoji: "🐝", name: "honeybee", category: "animals", keywords: ["bee", "honey"] },
  { emoji: "🐛", name: "bug", category: "animals", keywords: ["bug", "insect"] },
  { emoji: "🦋", name: "butterfly", category: "animals", keywords: ["butterfly", "insect"] },
  { emoji: "🐌", name: "snail", category: "animals", keywords: ["snail", "slow"] },
  { emoji: "🐙", name: "octopus", category: "animals", keywords: ["octopus", "sea"] },
  { emoji: "🦑", name: "squid", category: "animals", keywords: ["squid", "sea"] },
  { emoji: "🦐", name: "shrimp", category: "animals", keywords: ["shrimp", "seafood"] },
  { emoji: "🦀", name: "crab", category: "animals", keywords: ["crab", "seafood"] },
  { emoji: "🐠", name: "tropical fish", category: "animals", keywords: ["fish", "sea"] },
  { emoji: "🐟", name: "fish", category: "animals", keywords: ["fish", "sea"] },
  { emoji: "🐬", name: "dolphin", category: "animals", keywords: ["dolphin", "sea"] },
  { emoji: "🐳", name: "spouting whale", category: "animals", keywords: ["whale", "sea"] },
  { emoji: "🦈", name: "shark", category: "animals", keywords: ["shark", "sea"] },
  { emoji: "🐊", name: "crocodile", category: "animals", keywords: ["crocodile", "alligator"] },
  { emoji: "🐢", name: "turtle", category: "animals", keywords: ["turtle", "slow"] },
  { emoji: "🦎", name: "lizard", category: "animals", keywords: ["lizard", "reptile"] },
  { emoji: "🐍", name: "snake", category: "animals", keywords: ["snake", "reptile"] },
  { emoji: "🐲", name: "dragon face", category: "animals", keywords: ["dragon", "fantasy"] },
  { emoji: "🌵", name: "cactus", category: "animals", keywords: ["cactus", "desert"] },
  { emoji: "🌲", name: "evergreen tree", category: "animals", keywords: ["tree", "nature"] },
  { emoji: "🌳", name: "deciduous tree", category: "animals", keywords: ["tree", "nature"] },
  { emoji: "🌴", name: "palm tree", category: "animals", keywords: ["palm", "tropical"] },
  { emoji: "🌱", name: "seedling", category: "animals", keywords: ["plant", "grow"] },
  { emoji: "🌿", name: "herb", category: "animals", keywords: ["herb", "plant"] },
  { emoji: "🍀", name: "four leaf clover", category: "animals", keywords: ["luck", "clover"] },
  { emoji: "🌸", name: "cherry blossom", category: "animals", keywords: ["flower", "spring"] },
  { emoji: "🌹", name: "rose", category: "animals", keywords: ["flower", "love"] },
  { emoji: "🌻", name: "sunflower", category: "animals", keywords: ["flower", "sun"] },
  { emoji: "🌺", name: "hibiscus", category: "animals", keywords: ["flower", "tropical"] },
  { emoji: "🌷", name: "tulip", category: "animals", keywords: ["flower", "spring"] },
  { emoji: "🌼", name: "blossom", category: "animals", keywords: ["flower"] },
  { emoji: "🌾", name: "sheaf of rice", category: "animals", keywords: ["rice", "grain"] },

  // Food & Drinks
  { emoji: "🍎", name: "red apple", category: "food", keywords: ["apple", "fruit"] },
  { emoji: "🍊", name: "tangerine", category: "food", keywords: ["orange", "fruit"] },
  { emoji: "🍋", name: "lemon", category: "food", keywords: ["lemon", "fruit", "sour"] },
  { emoji: "🍌", name: "banana", category: "food", keywords: ["banana", "fruit"] },
  { emoji: "🍉", name: "watermelon", category: "food", keywords: ["watermelon", "fruit", "summer"] },
  { emoji: "🍇", name: "grapes", category: "food", keywords: ["grapes", "fruit", "wine"] },
  { emoji: "🍓", name: "strawberry", category: "food", keywords: ["strawberry", "fruit"] },
  { emoji: "🫐", name: "blueberries", category: "food", keywords: ["blueberry", "fruit"] },
  { emoji: "🍈", name: "melon", category: "food", keywords: ["melon", "fruit"] },
  { emoji: "🍒", name: "cherries", category: "food", keywords: ["cherry", "fruit"] },
  { emoji: "🍑", name: "peach", category: "food", keywords: ["peach", "fruit"] },
  { emoji: "🥭", name: "mango", category: "food", keywords: ["mango", "fruit", "tropical"] },
  { emoji: "🍍", name: "pineapple", category: "food", keywords: ["pineapple", "fruit", "tropical"] },
  { emoji: "🥥", name: "coconut", category: "food", keywords: ["coconut", "tropical"] },
  { emoji: "🥝", name: "kiwi fruit", category: "food", keywords: ["kiwi", "fruit"] },
  { emoji: "🍅", name: "tomato", category: "food", keywords: ["tomato", "vegetable"] },
  { emoji: "🥑", name: "avocado", category: "food", keywords: ["avocado", "guacamole"] },
  { emoji: "🍆", name: "eggplant", category: "food", keywords: ["eggplant", "aubergine"] },
  { emoji: "🥔", name: "potato", category: "food", keywords: ["potato", "vegetable"] },
  { emoji: "🥕", name: "carrot", category: "food", keywords: ["carrot", "vegetable"] },
  { emoji: "🌽", name: "ear of corn", category: "food", keywords: ["corn", "vegetable"] },
  { emoji: "🌶️", name: "hot pepper", category: "food", keywords: ["pepper", "spicy"] },
  { emoji: "🥒", name: "cucumber", category: "food", keywords: ["cucumber", "vegetable"] },
  { emoji: "🥬", name: "leafy green", category: "food", keywords: ["lettuce", "vegetable"] },
  { emoji: "🥦", name: "broccoli", category: "food", keywords: ["broccoli", "vegetable"] },
  { emoji: "🧄", name: "garlic", category: "food", keywords: ["garlic", "vegetable"] },
  { emoji: "🧅", name: "onion", category: "food", keywords: ["onion", "vegetable"] },
  { emoji: "🍄", name: "mushroom", category: "food", keywords: ["mushroom", "vegetable"] },
  { emoji: "🥜", name: "peanuts", category: "food", keywords: ["peanut", "nut"] },
  { emoji: "🍞", name: "bread", category: "food", keywords: ["bread", "bakery"] },
  { emoji: "🥐", name: "croissant", category: "food", keywords: ["croissant", "bakery", "french"] },
  { emoji: "🥖", name: "baguette bread", category: "food", keywords: ["baguette", "french"] },
  { emoji: "🥨", name: "pretzel", category: "food", keywords: ["pretzel", "snack"] },
  { emoji: "🧀", name: "cheese wedge", category: "food", keywords: ["cheese", "dairy"] },
  { emoji: "🥚", name: "egg", category: "food", keywords: ["egg", "breakfast"] },
  { emoji: "🍳", name: "cooking", category: "food", keywords: ["egg", "frying pan", "breakfast"] },
  { emoji: "🥞", name: "pancakes", category: "food", keywords: ["pancake", "breakfast"] },
  { emoji: "🧇", name: "waffle", category: "food", keywords: ["waffle", "breakfast"] },
  { emoji: "🥓", name: "bacon", category: "food", keywords: ["bacon", "breakfast"] },
  { emoji: "🍔", name: "hamburger", category: "food", keywords: ["burger", "fast food"] },
  { emoji: "🍟", name: "french fries", category: "food", keywords: ["fries", "fast food"] },
  { emoji: "🍕", name: "pizza", category: "food", keywords: ["pizza", "italian"] },
  { emoji: "🌭", name: "hot dog", category: "food", keywords: ["hotdog", "fast food"] },
  { emoji: "🥪", name: "sandwich", category: "food", keywords: ["sandwich", "lunch"] },
  { emoji: "🌮", name: "taco", category: "food", keywords: ["taco", "mexican"] },
  { emoji: "🌯", name: "burrito", category: "food", keywords: ["burrito", "mexican"] },
  { emoji: "🥗", name: "green salad", category: "food", keywords: ["salad", "healthy"] },
  { emoji: "🍝", name: "spaghetti", category: "food", keywords: ["pasta", "italian"] },
  { emoji: "🍜", name: "steaming bowl", category: "food", keywords: ["ramen", "noodles", "soup"] },
  { emoji: "🍲", name: "pot of food", category: "food", keywords: ["stew", "soup"] },
  { emoji: "🍛", name: "curry rice", category: "food", keywords: ["curry", "indian"] },
  { emoji: "🍣", name: "sushi", category: "food", keywords: ["sushi", "japanese"] },
  { emoji: "🍱", name: "bento box", category: "food", keywords: ["bento", "japanese", "lunch"] },
  { emoji: "🥟", name: "dumpling", category: "food", keywords: ["dumpling", "asian"] },
  { emoji: "🍤", name: "fried shrimp", category: "food", keywords: ["shrimp", "tempura"] },
  { emoji: "🍙", name: "rice ball", category: "food", keywords: ["onigiri", "japanese"] },
  { emoji: "🍚", name: "cooked rice", category: "food", keywords: ["rice", "asian"] },
  { emoji: "🍘", name: "rice cracker", category: "food", keywords: ["rice cracker", "japanese"] },
  { emoji: "🍧", name: "shaved ice", category: "food", keywords: ["dessert", "ice"] },
  { emoji: "🍨", name: "ice cream", category: "food", keywords: ["ice cream", "dessert"] },
  { emoji: "🍦", name: "soft ice cream", category: "food", keywords: ["ice cream", "dessert"] },
  { emoji: "🥧", name: "pie", category: "food", keywords: ["pie", "dessert"] },
  { emoji: "🧁", name: "cupcake", category: "food", keywords: ["cupcake", "dessert"] },
  { emoji: "🍰", name: "shortcake", category: "food", keywords: ["cake", "dessert"] },
  { emoji: "🎂", name: "birthday cake", category: "food", keywords: ["cake", "birthday"] },
  { emoji: "🍮", name: "custard", category: "food", keywords: ["pudding", "dessert"] },
  { emoji: "🍭", name: "lollipop", category: "food", keywords: ["candy", "sweet"] },
  { emoji: "🍬", name: "candy", category: "food", keywords: ["candy", "sweet"] },
  { emoji: "🍫", name: "chocolate bar", category: "food", keywords: ["chocolate", "sweet"] },
  { emoji: "🍿", name: "popcorn", category: "food", keywords: ["popcorn", "movie", "snack"] },
  { emoji: "🍩", name: "doughnut", category: "food", keywords: ["donut", "dessert"] },
  { emoji: "🍪", name: "cookie", category: "food", keywords: ["cookie", "biscuit"] },
  { emoji: "☕", name: "hot beverage", category: "food", keywords: ["coffee", "tea", "hot"] },
  { emoji: "🍵", name: "teacup without handle", category: "food", keywords: ["tea", "matcha"] },
  { emoji: "🧃", name: "beverage box", category: "food", keywords: ["juice", "box"] },
  { emoji: "🥤", name: "cup with straw", category: "food", keywords: ["soda", "drink"] },
  { emoji: "🧋", name: "bubble tea", category: "food", keywords: ["boba", "milk tea"] },
  { emoji: "🍺", name: "beer mug", category: "food", keywords: ["beer", "alcohol"] },
  { emoji: "🍻", name: "clinking beer mugs", category: "food", keywords: ["beer", "cheers"] },
  { emoji: "🥂", name: "clinking glasses", category: "food", keywords: ["champagne", "toast"] },
  { emoji: "🍷", name: "wine glass", category: "food", keywords: ["wine", "alcohol"] },
  { emoji: "🥃", name: "tumbler glass", category: "food", keywords: ["whiskey", "alcohol"] },
  { emoji: "🍸", name: "cocktail glass", category: "food", keywords: ["cocktail", "martini"] },
  { emoji: "🧊", name: "ice", category: "food", keywords: ["ice", "cold"] },

  // Travel & Places
  { emoji: "🚗", name: "automobile", category: "travel", keywords: ["car", "drive"] },
  { emoji: "🚕", name: "taxi", category: "travel", keywords: ["taxi", "cab"] },
  { emoji: "🚙", name: "sport utility vehicle", category: "travel", keywords: ["suv", "car"] },
  { emoji: "🚌", name: "bus", category: "travel", keywords: ["bus", "transport"] },
  { emoji: "🚎", name: "trolleybus", category: "travel", keywords: ["trolley", "bus"] },
  { emoji: "🏎️", name: "racing car", category: "travel", keywords: ["race", "car", "fast"] },
  { emoji: "🚓", name: "police car", category: "travel", keywords: ["police", "car"] },
  { emoji: "🚑", name: "ambulance", category: "travel", keywords: ["ambulance", "emergency"] },
  { emoji: "🚒", name: "fire engine", category: "travel", keywords: ["fire truck", "emergency"] },
  { emoji: "🚐", name: "minibus", category: "travel", keywords: ["van", "bus"] },
  { emoji: "🛻", name: "pickup truck", category: "travel", keywords: ["truck", "pickup"] },
  { emoji: "🚚", name: "delivery truck", category: "travel", keywords: ["truck", "delivery"] },
  { emoji: "🚛", name: "articulated lorry", category: "travel", keywords: ["truck", "semi"] },
  { emoji: "🚜", name: "tractor", category: "travel", keywords: ["tractor", "farm"] },
  { emoji: "🏍️", name: "motorcycle", category: "travel", keywords: ["motorcycle", "bike"] },
  { emoji: "🛵", name: "motor scooter", category: "travel", keywords: ["scooter", "vespa"] },
  { emoji: "🚲", name: "bicycle", category: "travel", keywords: ["bike", "cycle"] },
  { emoji: "🛴", name: "kick scooter", category: "travel", keywords: ["scooter"] },
  { emoji: "✈️", name: "airplane", category: "travel", keywords: ["plane", "fly", "travel"] },
  { emoji: "🛫", name: "airplane departure", category: "travel", keywords: ["takeoff", "flight"] },
  { emoji: "🛬", name: "airplane arrival", category: "travel", keywords: ["landing", "flight"] },
  { emoji: "🚀", name: "rocket", category: "travel", keywords: ["rocket", "space", "launch"] },
  { emoji: "🛸", name: "flying saucer", category: "travel", keywords: ["ufo", "alien"] },
  { emoji: "🚁", name: "helicopter", category: "travel", keywords: ["helicopter", "chopper"] },
  { emoji: "⛵", name: "sailboat", category: "travel", keywords: ["boat", "sail"] },
  { emoji: "🚤", name: "speedboat", category: "travel", keywords: ["boat", "speed"] },
  { emoji: "🛥️", name: "motor boat", category: "travel", keywords: ["boat"] },
  { emoji: "🛳️", name: "passenger ship", category: "travel", keywords: ["cruise", "ship"] },
  { emoji: "⛴️", name: "ferry", category: "travel", keywords: ["ferry", "boat"] },
  { emoji: "🚢", name: "ship", category: "travel", keywords: ["ship", "boat"] },
  { emoji: "🚂", name: "locomotive", category: "travel", keywords: ["train", "steam"] },
  { emoji: "🚃", name: "railway car", category: "travel", keywords: ["train", "subway"] },
  { emoji: "🚄", name: "high-speed train", category: "travel", keywords: ["train", "fast"] },
  { emoji: "🚅", name: "bullet train", category: "travel", keywords: ["shinkansen", "train"] },
  { emoji: "🚆", name: "train", category: "travel", keywords: ["train"] },
  { emoji: "🚇", name: "metro", category: "travel", keywords: ["subway", "metro"] },
  { emoji: "🚈", name: "light rail", category: "travel", keywords: ["train", "rail"] },
  { emoji: "🚊", name: "tram", category: "travel", keywords: ["tram", "streetcar"] },
  { emoji: "🏠", name: "house", category: "travel", keywords: ["house", "home"] },
  { emoji: "🏡", name: "house with garden", category: "travel", keywords: ["house", "home", "garden"] },
  { emoji: "🏢", name: "office building", category: "travel", keywords: ["office", "building", "work"] },
  { emoji: "🏣", name: "Japanese post office", category: "travel", keywords: ["post office"] },
  { emoji: "🏥", name: "hospital", category: "travel", keywords: ["hospital", "medical"] },
  { emoji: "🏦", name: "bank", category: "travel", keywords: ["bank", "money"] },
  { emoji: "🏨", name: "hotel", category: "travel", keywords: ["hotel", "travel"] },
  { emoji: "🏩", name: "love hotel", category: "travel", keywords: ["hotel", "love"] },
  { emoji: "🏪", name: "convenience store", category: "travel", keywords: ["store", "shop"] },
  { emoji: "🏫", name: "school", category: "travel", keywords: ["school", "education"] },
  { emoji: "🏬", name: "department store", category: "travel", keywords: ["store", "shopping"] },
  { emoji: "🏭", name: "factory", category: "travel", keywords: ["factory", "industry"] },
  { emoji: "🏯", name: "Japanese castle", category: "travel", keywords: ["castle", "japan"] },
  { emoji: "🏰", name: "castle", category: "travel", keywords: ["castle", "medieval"] },
  { emoji: "💒", name: "wedding", category: "travel", keywords: ["wedding", "chapel"] },
  { emoji: "🗼", name: "Tokyo tower", category: "travel", keywords: ["tokyo", "tower"] },
  { emoji: "🗽", name: "Statue of Liberty", category: "travel", keywords: ["statue", "liberty", "usa"] },
  { emoji: "⛪", name: "church", category: "travel", keywords: ["church", "religion"] },
  { emoji: "🕌", name: "mosque", category: "travel", keywords: ["mosque", "islam"] },
  { emoji: "🛕", name: "hindu temple", category: "travel", keywords: ["temple", "hindu"] },
  { emoji: "🕍", name: "synagogue", category: "travel", keywords: ["synagogue", "jewish"] },
  { emoji: "⛩️", name: "shinto shrine", category: "travel", keywords: ["shrine", "japan"] },
  { emoji: "🕋", name: "kaaba", category: "travel", keywords: ["kaaba", "mecca", "islam"] },
  { emoji: "⛲", name: "fountain", category: "travel", keywords: ["fountain", "park"] },
  { emoji: "🌅", name: "sunrise", category: "travel", keywords: ["sunrise", "morning"] },
  { emoji: "🌄", name: "sunrise over mountains", category: "travel", keywords: ["sunrise", "mountain"] },
  { emoji: "🌃", name: "night with stars", category: "travel", keywords: ["night", "city", "stars"] },
  { emoji: "🌉", name: "bridge at night", category: "travel", keywords: ["bridge", "night"] },
  { emoji: "🌌", name: "milky way", category: "travel", keywords: ["galaxy", "space", "stars"] },
  { emoji: "🏝️", name: "desert island", category: "travel", keywords: ["island", "beach"] },
  { emoji: "🏖️", name: "beach with umbrella", category: "travel", keywords: ["beach", "vacation"] },
  { emoji: "🏕️", name: "camping", category: "travel", keywords: ["camping", "tent"] },
  { emoji: "🌋", name: "volcano", category: "travel", keywords: ["volcano", "nature"] },
  { emoji: "🏔️", name: "snow-capped mountain", category: "travel", keywords: ["mountain", "snow"] },
  { emoji: "⛰️", name: "mountain", category: "travel", keywords: ["mountain", "nature"] },
  { emoji: "🗻", name: "mount fuji", category: "travel", keywords: ["fuji", "japan", "mountain"] },
  { emoji: "🌍", name: "globe showing Europe-Africa", category: "travel", keywords: ["earth", "world"] },
  { emoji: "🌎", name: "globe showing Americas", category: "travel", keywords: ["earth", "world"] },
  { emoji: "🌏", name: "globe showing Asia-Australia", category: "travel", keywords: ["earth", "world"] },

  // Activities & Sports
  { emoji: "⚽", name: "soccer ball", category: "activities", keywords: ["soccer", "football", "sport"] },
  { emoji: "🏀", name: "basketball", category: "activities", keywords: ["basketball", "sport"] },
  { emoji: "🏈", name: "american football", category: "activities", keywords: ["football", "sport"] },
  { emoji: "⚾", name: "baseball", category: "activities", keywords: ["baseball", "sport"] },
  { emoji: "🥎", name: "softball", category: "activities", keywords: ["softball", "sport"] },
  { emoji: "🎾", name: "tennis", category: "activities", keywords: ["tennis", "sport"] },
  { emoji: "🏐", name: "volleyball", category: "activities", keywords: ["volleyball", "sport"] },
  { emoji: "🏉", name: "rugby football", category: "activities", keywords: ["rugby", "sport"] },
  { emoji: "🥏", name: "flying disc", category: "activities", keywords: ["frisbee", "sport"] },
  { emoji: "🎱", name: "pool 8 ball", category: "activities", keywords: ["billiards", "pool"] },
  { emoji: "🏓", name: "ping pong", category: "activities", keywords: ["table tennis", "sport"] },
  { emoji: "🏸", name: "badminton", category: "activities", keywords: ["badminton", "sport"] },
  { emoji: "🏒", name: "ice hockey", category: "activities", keywords: ["hockey", "sport"] },
  { emoji: "🏑", name: "field hockey", category: "activities", keywords: ["hockey", "sport"] },
  { emoji: "🥍", name: "lacrosse", category: "activities", keywords: ["lacrosse", "sport"] },
  { emoji: "🏏", name: "cricket game", category: "activities", keywords: ["cricket", "sport"] },
  { emoji: "🥅", name: "goal net", category: "activities", keywords: ["goal", "sport"] },
  { emoji: "⛳", name: "flag in hole", category: "activities", keywords: ["golf", "sport"] },
  { emoji: "🏌️", name: "person golfing", category: "activities", keywords: ["golf", "sport"] },
  { emoji: "🏇", name: "horse racing", category: "activities", keywords: ["horse", "racing"] },
  { emoji: "⛷️", name: "skier", category: "activities", keywords: ["ski", "winter"] },
  { emoji: "🏂", name: "snowboarder", category: "activities", keywords: ["snowboard", "winter"] },
  { emoji: "🏋️", name: "person lifting weights", category: "activities", keywords: ["gym", "workout"] },
  { emoji: "🤼", name: "people wrestling", category: "activities", keywords: ["wrestling", "sport"] },
  { emoji: "🤸", name: "person cartwheeling", category: "activities", keywords: ["gymnastics", "sport"] },
  { emoji: "🤺", name: "person fencing", category: "activities", keywords: ["fencing", "sport"] },
  { emoji: "⛹️", name: "person bouncing ball", category: "activities", keywords: ["basketball", "sport"] },
  { emoji: "🤾", name: "person playing handball", category: "activities", keywords: ["handball", "sport"] },
  { emoji: "🧘", name: "person in lotus position", category: "activities", keywords: ["yoga", "meditation"] },
  { emoji: "🏄", name: "person surfing", category: "activities", keywords: ["surf", "beach"] },
  { emoji: "🏊", name: "person swimming", category: "activities", keywords: ["swim", "pool"] },
  { emoji: "🤽", name: "person playing water polo", category: "activities", keywords: ["water polo", "sport"] },
  { emoji: "🚣", name: "person rowing boat", category: "activities", keywords: ["rowing", "boat"] },
  { emoji: "🧗", name: "person climbing", category: "activities", keywords: ["climbing", "sport"] },
  { emoji: "🚵", name: "person mountain biking", category: "activities", keywords: ["biking", "sport"] },
  { emoji: "🚴", name: "person biking", category: "activities", keywords: ["cycling", "bike"] },
  { emoji: "🏆", name: "trophy", category: "activities", keywords: ["trophy", "winner", "prize"] },
  { emoji: "🥇", name: "1st place medal", category: "activities", keywords: ["gold", "medal", "winner"] },
  { emoji: "🥈", name: "2nd place medal", category: "activities", keywords: ["silver", "medal"] },
  { emoji: "🥉", name: "3rd place medal", category: "activities", keywords: ["bronze", "medal"] },
  { emoji: "🏅", name: "sports medal", category: "activities", keywords: ["medal", "award"] },
  { emoji: "🎖️", name: "military medal", category: "activities", keywords: ["medal", "award"] },
  { emoji: "🎗️", name: "reminder ribbon", category: "activities", keywords: ["ribbon", "awareness"] },
  { emoji: "🎪", name: "circus tent", category: "activities", keywords: ["circus", "tent"] },
  { emoji: "🎭", name: "performing arts", category: "activities", keywords: ["theater", "drama"] },
  { emoji: "🎨", name: "artist palette", category: "activities", keywords: ["art", "paint"] },
  { emoji: "🎬", name: "clapper board", category: "activities", keywords: ["movie", "film"] },
  { emoji: "🎤", name: "microphone", category: "activities", keywords: ["mic", "sing", "karaoke"] },
  { emoji: "🎧", name: "headphone", category: "activities", keywords: ["headphones", "music"] },
  { emoji: "🎼", name: "musical score", category: "activities", keywords: ["music", "notes"] },
  { emoji: "🎹", name: "musical keyboard", category: "activities", keywords: ["piano", "music"] },
  { emoji: "🎷", name: "saxophone", category: "activities", keywords: ["sax", "jazz", "music"] },
  { emoji: "🎺", name: "trumpet", category: "activities", keywords: ["trumpet", "music"] },
  { emoji: "🎸", name: "guitar", category: "activities", keywords: ["guitar", "rock", "music"] },
  { emoji: "🪕", name: "banjo", category: "activities", keywords: ["banjo", "country", "music"] },
  { emoji: "🎻", name: "violin", category: "activities", keywords: ["violin", "music"] },
  { emoji: "🥁", name: "drum", category: "activities", keywords: ["drum", "music"] },
  { emoji: "🎲", name: "game die", category: "activities", keywords: ["dice", "game"] },
  { emoji: "🎯", name: "direct hit", category: "activities", keywords: ["target", "bullseye"] },
  { emoji: "🎳", name: "bowling", category: "activities", keywords: ["bowling", "game"] },
  { emoji: "🎮", name: "video game", category: "activities", keywords: ["game", "controller", "gaming"] },
  { emoji: "🎰", name: "slot machine", category: "activities", keywords: ["slot", "casino", "gambling"] },
  { emoji: "🧩", name: "puzzle piece", category: "activities", keywords: ["puzzle", "game"] },

  // Objects & Symbols
  { emoji: "💡", name: "light bulb", category: "objects", keywords: ["idea", "light", "bright"] },
  { emoji: "🔦", name: "flashlight", category: "objects", keywords: ["flashlight", "light"] },
  { emoji: "🕯️", name: "candle", category: "objects", keywords: ["candle", "light"] },
  { emoji: "📱", name: "mobile phone", category: "objects", keywords: ["phone", "smartphone", "mobile"] },
  { emoji: "📲", name: "mobile phone with arrow", category: "objects", keywords: ["call", "phone"] },
  { emoji: "💻", name: "laptop", category: "objects", keywords: ["computer", "laptop", "pc"] },
  { emoji: "🖥️", name: "desktop computer", category: "objects", keywords: ["computer", "desktop", "pc"] },
  { emoji: "🖨️", name: "printer", category: "objects", keywords: ["printer", "print"] },
  { emoji: "⌨️", name: "keyboard", category: "objects", keywords: ["keyboard", "type"] },
  { emoji: "🖱️", name: "computer mouse", category: "objects", keywords: ["mouse", "computer"] },
  { emoji: "💾", name: "floppy disk", category: "objects", keywords: ["disk", "save"] },
  { emoji: "💿", name: "optical disk", category: "objects", keywords: ["cd", "disk"] },
  { emoji: "📀", name: "dvd", category: "objects", keywords: ["dvd", "disk"] },
  { emoji: "🎵", name: "musical note", category: "objects", keywords: ["music", "note"] },
  { emoji: "🎶", name: "musical notes", category: "objects", keywords: ["music", "notes"] },
  { emoji: "📻", name: "radio", category: "objects", keywords: ["radio", "music"] },
  { emoji: "📺", name: "television", category: "objects", keywords: ["tv", "television"] },
  { emoji: "📷", name: "camera", category: "objects", keywords: ["camera", "photo"] },
  { emoji: "📸", name: "camera with flash", category: "objects", keywords: ["camera", "photo", "flash"] },
  { emoji: "📹", name: "video camera", category: "objects", keywords: ["video", "camera", "film"] },
  { emoji: "🎥", name: "movie camera", category: "objects", keywords: ["movie", "camera", "film"] },
  { emoji: "📽️", name: "film projector", category: "objects", keywords: ["projector", "film"] },
  { emoji: "🔍", name: "magnifying glass tilted left", category: "objects", keywords: ["search", "zoom"] },
  { emoji: "🔎", name: "magnifying glass tilted right", category: "objects", keywords: ["search", "zoom"] },
  { emoji: "📖", name: "open book", category: "objects", keywords: ["book", "read"] },
  { emoji: "📚", name: "books", category: "objects", keywords: ["books", "library", "study"] },
  { emoji: "📝", name: "memo", category: "objects", keywords: ["note", "memo", "write"] },
  { emoji: "✏️", name: "pencil", category: "objects", keywords: ["pencil", "write"] },
  { emoji: "🖊️", name: "pen", category: "objects", keywords: ["pen", "write"] },
  { emoji: "📌", name: "pushpin", category: "objects", keywords: ["pin", "note"] },
  { emoji: "📎", name: "paperclip", category: "objects", keywords: ["clip", "attach"] },
  { emoji: "📁", name: "file folder", category: "objects", keywords: ["folder", "file"] },
  { emoji: "📂", name: "open file folder", category: "objects", keywords: ["folder", "file"] },
  { emoji: "📅", name: "calendar", category: "objects", keywords: ["calendar", "date"] },
  { emoji: "📆", name: "tear-off calendar", category: "objects", keywords: ["calendar", "date"] },
  { emoji: "📊", name: "bar chart", category: "objects", keywords: ["chart", "graph", "stats"] },
  { emoji: "📈", name: "chart increasing", category: "objects", keywords: ["growth", "chart"] },
  { emoji: "📉", name: "chart decreasing", category: "objects", keywords: ["decline", "chart"] },
  { emoji: "✉️", name: "envelope", category: "objects", keywords: ["mail", "email", "letter"] },
  { emoji: "📧", name: "e-mail", category: "objects", keywords: ["email", "mail"] },
  { emoji: "📩", name: "envelope with arrow", category: "objects", keywords: ["email", "receive"] },
  { emoji: "📨", name: "incoming envelope", category: "objects", keywords: ["email", "inbox"] },
  { emoji: "📤", name: "outbox tray", category: "objects", keywords: ["outbox", "send"] },
  { emoji: "📥", name: "inbox tray", category: "objects", keywords: ["inbox", "receive"] },
  { emoji: "📦", name: "package", category: "objects", keywords: ["box", "package", "delivery"] },
  { emoji: "🔐", name: "locked with key", category: "objects", keywords: ["lock", "secure"] },
  { emoji: "🔑", name: "key", category: "objects", keywords: ["key", "unlock"] },
  { emoji: "🔒", name: "locked", category: "objects", keywords: ["lock", "secure", "closed"] },
  { emoji: "🔓", name: "unlocked", category: "objects", keywords: ["unlock", "open"] },
  { emoji: "🔔", name: "bell", category: "objects", keywords: ["bell", "notification"] },
  { emoji: "🔕", name: "bell with slash", category: "objects", keywords: ["mute", "silent"] },
  { emoji: "🔊", name: "speaker high volume", category: "objects", keywords: ["volume", "loud"] },
  { emoji: "🔇", name: "muted speaker", category: "objects", keywords: ["mute", "silent"] },
  { emoji: "⏰", name: "alarm clock", category: "objects", keywords: ["alarm", "clock", "time"] },
  { emoji: "⏱️", name: "stopwatch", category: "objects", keywords: ["timer", "stopwatch"] },
  { emoji: "⌚", name: "watch", category: "objects", keywords: ["watch", "time"] },
  { emoji: "🛒", name: "shopping cart", category: "objects", keywords: ["cart", "shopping"] },
  { emoji: "💰", name: "money bag", category: "objects", keywords: ["money", "cash", "rich"] },
  { emoji: "💵", name: "dollar banknote", category: "objects", keywords: ["money", "dollar", "cash"] },
  { emoji: "💴", name: "yen banknote", category: "objects", keywords: ["money", "yen", "japan"] },
  { emoji: "💶", name: "euro banknote", category: "objects", keywords: ["money", "euro"] },
  { emoji: "💷", name: "pound banknote", category: "objects", keywords: ["money", "pound", "uk"] },
  { emoji: "💳", name: "credit card", category: "objects", keywords: ["card", "credit", "payment"] },
  { emoji: "💎", name: "gem stone", category: "objects", keywords: ["diamond", "gem", "jewel"] },
  { emoji: "⚙️", name: "gear", category: "objects", keywords: ["settings", "gear", "config"] },
  { emoji: "🔧", name: "wrench", category: "objects", keywords: ["tool", "wrench", "fix"] },
  { emoji: "🔨", name: "hammer", category: "objects", keywords: ["tool", "hammer", "build"] },
  { emoji: "⚡", name: "high voltage", category: "objects", keywords: ["lightning", "power", "energy"] },
  { emoji: "🔥", name: "fire", category: "objects", keywords: ["fire", "hot", "flame"] },
  { emoji: "💧", name: "droplet", category: "objects", keywords: ["water", "drop"] },
  { emoji: "🌟", name: "glowing star", category: "objects", keywords: ["star", "shine", "sparkle"] },
  { emoji: "⭐", name: "star", category: "objects", keywords: ["star", "favorite"] },
  { emoji: "✨", name: "sparkles", category: "objects", keywords: ["sparkle", "shine", "magic"] },
  { emoji: "💫", name: "dizzy", category: "objects", keywords: ["star", "dizzy", "shooting"] },
  { emoji: "🌈", name: "rainbow", category: "objects", keywords: ["rainbow", "colors"] },
  { emoji: "☀️", name: "sun", category: "objects", keywords: ["sun", "sunny", "bright"] },
  { emoji: "🌙", name: "crescent moon", category: "objects", keywords: ["moon", "night"] },
  { emoji: "☁️", name: "cloud", category: "objects", keywords: ["cloud", "weather"] },
  { emoji: "🌧️", name: "cloud with rain", category: "objects", keywords: ["rain", "weather"] },
  { emoji: "❄️", name: "snowflake", category: "objects", keywords: ["snow", "cold", "winter"] },
  { emoji: "☔", name: "umbrella with rain drops", category: "objects", keywords: ["rain", "umbrella"] },
  { emoji: "✅", name: "check mark button", category: "objects", keywords: ["check", "done", "yes"] },
  { emoji: "❌", name: "cross mark", category: "objects", keywords: ["no", "wrong", "x"] },
  { emoji: "❓", name: "question mark", category: "objects", keywords: ["question", "help"] },
  { emoji: "❗", name: "exclamation mark", category: "objects", keywords: ["exclamation", "important"] },
  { emoji: "💯", name: "hundred points", category: "objects", keywords: ["100", "perfect", "score"] },
  { emoji: "🔴", name: "red circle", category: "objects", keywords: ["red", "circle"] },
  { emoji: "🟠", name: "orange circle", category: "objects", keywords: ["orange", "circle"] },
  { emoji: "🟡", name: "yellow circle", category: "objects", keywords: ["yellow", "circle"] },
  { emoji: "🟢", name: "green circle", category: "objects", keywords: ["green", "circle"] },
  { emoji: "🔵", name: "blue circle", category: "objects", keywords: ["blue", "circle"] },
  { emoji: "🟣", name: "purple circle", category: "objects", keywords: ["purple", "circle"] },
  { emoji: "⚪", name: "white circle", category: "objects", keywords: ["white", "circle"] },
  { emoji: "⚫", name: "black circle", category: "objects", keywords: ["black", "circle"] },

  // Flags
  { emoji: "🏳️", name: "white flag", category: "flags", keywords: ["flag", "white", "surrender"] },
  { emoji: "🏴", name: "black flag", category: "flags", keywords: ["flag", "black"] },
  { emoji: "🚩", name: "triangular flag", category: "flags", keywords: ["flag", "red"] },
  { emoji: "🏁", name: "chequered flag", category: "flags", keywords: ["flag", "race", "finish"] },
  { emoji: "🎌", name: "crossed flags", category: "flags", keywords: ["flags", "japan"] },
  { emoji: "🏳️‍🌈", name: "rainbow flag", category: "flags", keywords: ["pride", "lgbtq", "rainbow"] },
  { emoji: "🇺🇸", name: "flag: United States", category: "flags", keywords: ["usa", "america", "flag"] },
  { emoji: "🇬🇧", name: "flag: United Kingdom", category: "flags", keywords: ["uk", "britain", "flag"] },
  { emoji: "🇯🇵", name: "flag: Japan", category: "flags", keywords: ["japan", "flag"] },
  { emoji: "🇰🇷", name: "flag: South Korea", category: "flags", keywords: ["korea", "flag"] },
  { emoji: "🇨🇳", name: "flag: China", category: "flags", keywords: ["china", "flag"] },
  { emoji: "🇫🇷", name: "flag: France", category: "flags", keywords: ["france", "flag"] },
  { emoji: "🇩🇪", name: "flag: Germany", category: "flags", keywords: ["germany", "flag"] },
  { emoji: "🇮🇹", name: "flag: Italy", category: "flags", keywords: ["italy", "flag"] },
  { emoji: "🇪🇸", name: "flag: Spain", category: "flags", keywords: ["spain", "flag"] },
  { emoji: "🇧🇷", name: "flag: Brazil", category: "flags", keywords: ["brazil", "flag"] },
  { emoji: "🇷🇺", name: "flag: Russia", category: "flags", keywords: ["russia", "flag"] },
  { emoji: "🇮🇳", name: "flag: India", category: "flags", keywords: ["india", "flag"] },
  { emoji: "🇦🇺", name: "flag: Australia", category: "flags", keywords: ["australia", "flag"] },
  { emoji: "🇨🇦", name: "flag: Canada", category: "flags", keywords: ["canada", "flag"] },
  { emoji: "🇲🇽", name: "flag: Mexico", category: "flags", keywords: ["mexico", "flag"] },
];

export function getEmojisByCategory(category: EmojiCategory | "all" | "recent", recentEmojis: string[] = []): Emoji[] {
  if (category === "all") {
    return EMOJI_DATA;
  }
  if (category === "recent") {
    return recentEmojis
      .map((emoji) => EMOJI_DATA.find((e) => e.emoji === emoji))
      .filter((e): e is Emoji => e !== undefined);
  }
  return EMOJI_DATA.filter((e) => e.category === category);
}

export function searchEmojis(query: string): Emoji[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return EMOJI_DATA;

  return EMOJI_DATA.filter((e) => {
    const nameMatch = e.name.toLowerCase().includes(lowerQuery);
    const keywordMatch = e.keywords?.some((k) => k.toLowerCase().includes(lowerQuery));
    return nameMatch || keywordMatch;
  });
}
