import { Hashtag, HashtagCategory } from "./types";

export const HASHTAG_DATA: Hashtag[] = [
  // Marketing
  { tag: "#marketing", category: "marketing" },
  { tag: "#digitalmarketing", category: "marketing" },
  { tag: "#socialmedia", category: "marketing" },
  { tag: "#contentmarketing", category: "marketing" },
  { tag: "#branding", category: "marketing" },
  { tag: "#marketingstrategy", category: "marketing" },
  { tag: "#onlinemarketing", category: "marketing" },
  { tag: "#emailmarketing", category: "marketing" },
  { tag: "#influencermarketing", category: "marketing" },
  { tag: "#seo", category: "marketing" },
  { tag: "#sem", category: "marketing" },
  { tag: "#ppc", category: "marketing" },
  { tag: "#growthhacking", category: "marketing" },
  { tag: "#affiliatemarketing", category: "marketing" },
  { tag: "#marketingtips", category: "marketing" },
  { tag: "#socialmediamarketing", category: "marketing" },
  { tag: "#contentcreator", category: "marketing" },
  { tag: "#viral", category: "marketing" },
  { tag: "#trending", category: "marketing" },
  { tag: "#advertising", category: "marketing" },
  { tag: "#ads", category: "marketing" },
  { tag: "#campaign", category: "marketing" },
  { tag: "#brand", category: "marketing" },
  { tag: "#promotion", category: "marketing" },
  { tag: "#leadgeneration", category: "marketing" },

  // Business
  { tag: "#business", category: "business" },
  { tag: "#entrepreneur", category: "business" },
  { tag: "#startup", category: "business" },
  { tag: "#success", category: "business" },
  { tag: "#smallbusiness", category: "business" },
  { tag: "#ceo", category: "business" },
  { tag: "#leadership", category: "business" },
  { tag: "#networking", category: "business" },
  { tag: "#businessowner", category: "business" },
  { tag: "#investment", category: "business" },
  { tag: "#finance", category: "business" },
  { tag: "#money", category: "business" },
  { tag: "#wealth", category: "business" },
  { tag: "#hustle", category: "business" },
  { tag: "#grind", category: "business" },
  { tag: "#mindset", category: "business" },
  { tag: "#goals", category: "business" },
  { tag: "#productivity", category: "business" },
  { tag: "#innovation", category: "business" },
  { tag: "#strategy", category: "business" },
  { tag: "#consulting", category: "business" },
  { tag: "#freelance", category: "business" },
  { tag: "#remotework", category: "business" },
  { tag: "#workfromhome", category: "business" },
  { tag: "#sidehustle", category: "business" },

  // Lifestyle
  { tag: "#lifestyle", category: "lifestyle" },
  { tag: "#motivation", category: "lifestyle" },
  { tag: "#inspiration", category: "lifestyle" },
  { tag: "#happiness", category: "lifestyle" },
  { tag: "#positivevibes", category: "lifestyle" },
  { tag: "#mindfulness", category: "lifestyle" },
  { tag: "#wellness", category: "lifestyle" },
  { tag: "#selfcare", category: "lifestyle" },
  { tag: "#selflove", category: "lifestyle" },
  { tag: "#mentalhealth", category: "lifestyle" },
  { tag: "#healthy", category: "lifestyle" },
  { tag: "#healthylifestyle", category: "lifestyle" },
  { tag: "#balance", category: "lifestyle" },
  { tag: "#peace", category: "lifestyle" },
  { tag: "#grateful", category: "lifestyle" },
  { tag: "#blessed", category: "lifestyle" },
  { tag: "#life", category: "lifestyle" },
  { tag: "#love", category: "lifestyle" },
  { tag: "#family", category: "lifestyle" },
  { tag: "#friends", category: "lifestyle" },
  { tag: "#weekend", category: "lifestyle" },
  { tag: "#goodvibes", category: "lifestyle" },
  { tag: "#photography", category: "lifestyle" },
  { tag: "#daily", category: "lifestyle" },
  { tag: "#instagood", category: "lifestyle" },

  // Travel
  { tag: "#travel", category: "travel" },
  { tag: "#wanderlust", category: "travel" },
  { tag: "#adventure", category: "travel" },
  { tag: "#explore", category: "travel" },
  { tag: "#vacation", category: "travel" },
  { tag: "#holiday", category: "travel" },
  { tag: "#travelgram", category: "travel" },
  { tag: "#travelphotography", category: "travel" },
  { tag: "#instatravel", category: "travel" },
  { tag: "#trip", category: "travel" },
  { tag: "#traveling", category: "travel" },
  { tag: "#travelblogger", category: "travel" },
  { tag: "#traveltheworld", category: "travel" },
  { tag: "#roadtrip", category: "travel" },
  { tag: "#backpacking", category: "travel" },
  { tag: "#beach", category: "travel" },
  { tag: "#mountains", category: "travel" },
  { tag: "#nature", category: "travel" },
  { tag: "#sunset", category: "travel" },
  { tag: "#landscape", category: "travel" },
  { tag: "#cityscape", category: "travel" },
  { tag: "#tourism", category: "travel" },
  { tag: "#passport", category: "travel" },
  { tag: "#flight", category: "travel" },
  { tag: "#hotel", category: "travel" },

  // Food
  { tag: "#foodie", category: "food" },
  { tag: "#foodporn", category: "food" },
  { tag: "#yummy", category: "food" },
  { tag: "#delicious", category: "food" },
  { tag: "#instafood", category: "food" },
  { tag: "#foodphotography", category: "food" },
  { tag: "#cooking", category: "food" },
  { tag: "#homemade", category: "food" },
  { tag: "#recipe", category: "food" },
  { tag: "#healthyfood", category: "food" },
  { tag: "#vegan", category: "food" },
  { tag: "#vegetarian", category: "food" },
  { tag: "#organic", category: "food" },
  { tag: "#breakfast", category: "food" },
  { tag: "#lunch", category: "food" },
  { tag: "#dinner", category: "food" },
  { tag: "#brunch", category: "food" },
  { tag: "#dessert", category: "food" },
  { tag: "#coffee", category: "food" },
  { tag: "#wine", category: "food" },
  { tag: "#restaurant", category: "food" },
  { tag: "#chef", category: "food" },
  { tag: "#baking", category: "food" },
  { tag: "#foodstagram", category: "food" },
  { tag: "#tasty", category: "food" },

  // Fashion
  { tag: "#fashion", category: "fashion" },
  { tag: "#style", category: "fashion" },
  { tag: "#ootd", category: "fashion" },
  { tag: "#outfitoftheday", category: "fashion" },
  { tag: "#fashionista", category: "fashion" },
  { tag: "#fashionblogger", category: "fashion" },
  { tag: "#streetstyle", category: "fashion" },
  { tag: "#lookbook", category: "fashion" },
  { tag: "#fashionstyle", category: "fashion" },
  { tag: "#outfit", category: "fashion" },
  { tag: "#shopping", category: "fashion" },
  { tag: "#beauty", category: "fashion" },
  { tag: "#makeup", category: "fashion" },
  { tag: "#skincare", category: "fashion" },
  { tag: "#accessories", category: "fashion" },
  { tag: "#jewelry", category: "fashion" },
  { tag: "#shoes", category: "fashion" },
  { tag: "#dress", category: "fashion" },
  { tag: "#luxury", category: "fashion" },
  { tag: "#designer", category: "fashion" },
  { tag: "#model", category: "fashion" },
  { tag: "#instafashion", category: "fashion" },
  { tag: "#streetwear", category: "fashion" },
  { tag: "#vintage", category: "fashion" },
  { tag: "#mensfashion", category: "fashion" },

  // Fitness
  { tag: "#fitness", category: "fitness" },
  { tag: "#workout", category: "fitness" },
  { tag: "#gym", category: "fitness" },
  { tag: "#fitnessmotivation", category: "fitness" },
  { tag: "#fit", category: "fitness" },
  { tag: "#training", category: "fitness" },
  { tag: "#exercise", category: "fitness" },
  { tag: "#bodybuilding", category: "fitness" },
  { tag: "#muscle", category: "fitness" },
  { tag: "#strong", category: "fitness" },
  { tag: "#personaltrainer", category: "fitness" },
  { tag: "#crossfit", category: "fitness" },
  { tag: "#yoga", category: "fitness" },
  { tag: "#running", category: "fitness" },
  { tag: "#cardio", category: "fitness" },
  { tag: "#weightloss", category: "fitness" },
  { tag: "#nutrition", category: "fitness" },
  { tag: "#protein", category: "fitness" },
  { tag: "#gains", category: "fitness" },
  { tag: "#legday", category: "fitness" },
  { tag: "#abs", category: "fitness" },
  { tag: "#gymlife", category: "fitness" },
  { tag: "#fitnessjourney", category: "fitness" },
  { tag: "#healthylifestyle", category: "fitness" },
  { tag: "#athlete", category: "fitness" },

  // Tech
  { tag: "#tech", category: "tech" },
  { tag: "#coding", category: "tech" },
  { tag: "#developer", category: "tech" },
  { tag: "#programming", category: "tech" },
  { tag: "#webdev", category: "tech" },
  { tag: "#software", category: "tech" },
  { tag: "#javascript", category: "tech" },
  { tag: "#python", category: "tech" },
  { tag: "#react", category: "tech" },
  { tag: "#nodejs", category: "tech" },
  { tag: "#ai", category: "tech" },
  { tag: "#machinelearning", category: "tech" },
  { tag: "#datascience", category: "tech" },
  { tag: "#cloud", category: "tech" },
  { tag: "#devops", category: "tech" },
  { tag: "#opensource", category: "tech" },
  { tag: "#github", category: "tech" },
  { tag: "#startup", category: "tech" },
  { tag: "#innovation", category: "tech" },
  { tag: "#technology", category: "tech" },
  { tag: "#frontend", category: "tech" },
  { tag: "#backend", category: "tech" },
  { tag: "#fullstack", category: "tech" },
  { tag: "#mobile", category: "tech" },
  { tag: "#app", category: "tech" },
];

export function getHashtagsByCategory(
  category: HashtagCategory | "all" | "recent",
  recentHashtags: string[] = []
): Hashtag[] {
  if (category === "all") {
    return HASHTAG_DATA;
  }
  if (category === "recent") {
    return recentHashtags
      .map((tag) => HASHTAG_DATA.find((h) => h.tag === tag))
      .filter((h): h is Hashtag => h !== undefined);
  }
  return HASHTAG_DATA.filter((h) => h.category === category);
}

export function searchHashtags(query: string): Hashtag[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return HASHTAG_DATA;

  // Remove # if present in query
  const cleanQuery = lowerQuery.startsWith("#") ? lowerQuery.slice(1) : lowerQuery;

  return HASHTAG_DATA.filter((h) => h.tag.toLowerCase().includes(cleanQuery));
}
